### ISSUE TITLE
Intergration will not start

### ISSUE THREAD

**Issue by jonny190** [dummylabs/thewatchman#158]
Ive downloaded and installed the 0.6.3 integration via HACS and after adding it in the integration in to 2024.11.1 it refuses to starts giving the below error:

2024-11-19 13:29:25.528 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Watchman for watchman
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/watchman/__init__.py", line 135, in async_setup_entry
    await parse_config(hass, reason="changes in watchman configuration")
  File "/config/custom_components/watchman/__init__.py", line 340, in parse_config
    entity_list, service_list, files_parsed, files_ignored = await parse(
                                                             ^^^^^^^^^^^^
  File "/config/custom_components/watchman/utils.py", line 272, in parse
    async for line in f:
  File "/usr/local/lib/python3.12/site-packages/anyio/_core/_fileio.py", line 74, in __aiter__
    line = await self.readline()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_core/_fileio.py", line 90, in readline
    return await to_thread.run_sync(self._fp.readline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by dummylabs** [comment]
I've just checked it on HA 2024.11.2 with no issues. It seems like an installation problem.

1. Did you install it from HACS?
2. Have you tried removing it via HACS and reinstalling it?
