### ISSUE TITLE
The Watchmen fail to install with "Config flow could not be loaded: {"message":"Invalid handler specified"}"

### ISSUE THREAD

**Issue by WillemGoosen** [dummylabs/thewatchman#72]
Hi All
Please help!!!

I just must have “The Watchman” installed on Home Assistant but after the latest update v0.6.0 it is not working anymore and in trying to remove and re-install I now get the following errors. Even trying to re-install an older version I still have problems.

Config flow could not be loaded: {"message":"Invalid handler specified"}

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/watchman/utils.py:12
Integration: Watchman ([documentation](https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Fdummylabs%2Fthewatchman%3Ffbclid%3DIwAR1SAjh_QcHJQEpZ-mTTrOVyVuPk30pGypIV8yx6AWV1dKDPC3UOvCeVkjU&h=AT11ove_auYKlQJAXI0cF_5wpu9lvKg7yVGO8qY-6EWWYsfu3yUsGYXtxUtJu9jYW_U-cVujIbzihbctCSn0EiCqhtlJL-1h75_ZuzZwjhFviqYzY_jx1SjIpsb0uKDsRQ&__tn__=-UK-R&c[0]=AT3s3IJvnH4nuEO4IsgPLSP1gOipnuMHSvirHeOxH7zG8B0pzuPh9EX3-VdjhXVwiANHJZG72irfg3qEMG2LxPLTcs_UmWxpuvzK4uowiopFv7trag8zmX2ZiaJ6gYY3PhQm57RMf0M8aQk0613xl4WhHSL4i3n9dbUln8Y), [issues](https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Fdummylabs%2Fthewatchman%2Fissues%3Ffbclid%3DIwAR0oV8xbW2UBPgzlGaozN61gebEsrmp_-sgyd01qvL8XonENntnLRj3bRN0&h=AT02BqRYN-Qdz-F7K-nQ4ys7n9JVrPhafsJl7O2BoCn7bOqS0M_7rvipd_HNWpyqFsfZSODBPYapGswTRYf5B358g4qcjPcNC-hdVRX26q5ihT5o8yYsJuNyNpWlCBHl9g&__tn__=-UK-R&c[0]=AT3s3IJvnH4nuEO4IsgPLSP1gOipnuMHSvirHeOxH7zG8B0pzuPh9EX3-VdjhXVwiANHJZG72irfg3qEMG2LxPLTcs_UmWxpuvzK4uowiopFv7trag8zmX2ZiaJ6gYY3PhQm57RMf0M8aQk0613xl4WhHSL4i3n9dbUln8Y))
First occurred: 8:21:33 PM (1 occurrences)
Last logged: 8:21:33 PM

Unexpected exception importing platform custom_components.watchman.config_flow

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 728, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 745, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/watchman/__init__.py", line 27, in <module>
from .coordinator import WatchmanCoordinator
File "/config/custom_components/watchman/coordinator.py", line 8, in <module>
from .utils import check_entitites, check_services, get_entity_state, fill
File "/config/custom_components/watchman/utils.py", line 12, in <module>
from prettytable import PrettyTable
File "/usr/local/lib/python3.10/site-packages/prettytable/__init__.py", line 1, in <module>
from .prettytable import (
File "/usr/local/lib/python3.10/site-packages/prettytable/prettytable.py", line 45, in <module>
import wcwidth
File "/usr/local/lib/python3.10/site-packages/wcwidth/__init__.py", line 12, in <module>
from .wcwidth import ZERO_WIDTH # noqa
File "/usr/local/lib/python3.10/site-packages/wcwidth/wcwidth.py", line 72, in <module>
from .table_zero import ZERO_WIDTH
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 879, in exec_module
File "<frozen importlib._bootstrap_external>", line 1012, in get_code
File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
Log Details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 8:21:33 PM (1 occurrences)
Last logged: 8:21:33 PM
Error occurred loading configuration flow for integration watchman: Exception importing custom_components.watchman.config_flow
Thanks Much Appreciated.

**Comment by dummylabs** [comment]
Hi, it seems like an issue with your setup. There were no updates to Watchman since June 2022 (my bad, hope to deliver new features soon), however it should work fine with the recent version of HA. I've just checked that by removing Watchman from HACS and then installed it again without any problems on 2022.12.8.

Could you please do the following:
1. Uninstall Watchman from **Settings->Devices and Services** 
2. Open HACS and remove Watchman integration
3. Make sure there is no `watchman` folder left in `/config/custom_components`
4. You may want to restart HA at this moment just to be on the safe side, though it is not required
5. Install Watchman integration via HACS (version 0.6.0) and restart Home Assistant
6. Install Watchman from **Settings->Devices and Services**

**Comment by WillemGoosen** [comment]
Hi 
I have tried steps 1 to 6 in uninstalling "The Watchman" even did it again before replying here.
In step 3, I had the custom_components folder open and watched as the watchman folder disappeared when uninstalling. To be sure I did do a HA & VM restart at this point. 
But still the same error.

**Comment by WillemGoosen** [comment]
At the bottom of the large error log the following is displayed:
ValueError: bad marshal data (invalid reference)

After the failed install a new folder is created within watchman:
__pycache__

This folder then has the following files:
__init__.cpython-310.pyc
const.cpython-310.pyc
coordinator.cpython-310.pyc
utils.cpython-310.pyc

My HA version:
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**Comment by WillemGoosen** [comment]
The folder is __pycache__
Two underscores before and after.

**Comment by dummylabs** [comment]
`__pycache__` is a service folder where Python keeps pre-compiled modules to reduce the launch time. 
Google says that a reason for "bad marshal data" error can be corrupted .pyc files (which actually are pre-compiled modules stored in` __pycache__` folder). This is strange since you've already removed the whole Watchyman component and installed it from scratch. Anyway, you can safely delete `__pycache__` folder at any time, the Python interpreter will re-create it after HA restart.

So far no ideas left. Since you have a hypervisor, may be a good idea to create another temporary VM with fresh Home Assistant install and HACS to check if Watchman works there. My guess is that something is wrong with the Python environment within the HA Operating System.

**Comment by WillemGoosen** [comment]
Hi
Thanks for the feedback. I am restoring an old vm backup and will test from there.

Again, thanks for the feedback.

Much appreciated.

Will let you know what worked.

Happy new year.

Willem HJ Goosen
078 423 4192 Mobile
Sent from my LG Mobile
________________________________

**Comment by WillemGoosen** [comment]
Hi all
Fortunately, I export my VirtualBox VM each month before commencing with updates.
So, I restored and re-updated with all working as they should including “The Watchmen”
Thanks for all your help much appreciated.
